# Generated by Django 5.2 on 2025-11-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('total_horas', models.PositiveIntegerField(default=240)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_calculado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SobretiempoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_calculado', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sobretiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.sobretiempo')),
                ('tipo_sobretiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.tiposobretiempo')),
            ],
        ),
    ]
