"""
Django settings for proy_vbc project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment when available.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-l!+0%o%q$d=b9)eh5q-zm*z99!u^&f(xq2q6fbcuvwe53u!#+&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Allow hosts from comma-separated env var, default empty list (localhost during dev)
_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] if _allowed else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'commerce',
    "nomina",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proy_vbc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proy_vbc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration: use PostgreSQL when environment variables are provided,
# otherwise fall back to the default SQLite used in development.
def _get_env(name, default=None):
    return os.environ.get(name, default)

DB_ENGINE = (_get_env('DB_ENGINE') or '').lower()

if DB_ENGINE == 'sqlserver':
    # Configuración para SQL Server con autenticación Windows
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': _get_env('DB_NAME', 'Ventas_Django'),
            'HOST': _get_env('DB_HOST', 'localhost'),
            'PORT': _get_env('DB_PORT', '1433'),
            'OPTIONS': {
                'driver': _get_env('DB_DRIVER', 'ODBC Driver 17 for SQL Server'),
                'trusted_connection': 'yes',  # Autenticación Windows
            },
        }
    }

elif DB_ENGINE in ('postgresql', 'psycopg2', 'django.db.backends.postgresql') or (_get_env('DB_NAME') and _get_env('DB_USER')):
    # Configuración para PostgreSQL
    _port = _get_env('DB_PORT', '5432')
    try:
        _port = int(_port) if _port else ''
    except ValueError:
        pass

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _get_env('DB_NAME', 'postgres'),
            'USER': _get_env('DB_USER', ''),
            'PASSWORD': _get_env('DB_PASSWORD', ''),
            'HOST': _get_env('DB_HOST', 'localhost'),
            'PORT': _port or '5432',
        }
    }

else:
    # Fallback: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

#-------------
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)  # carpeta fisica de archivos estaticos
# Directory where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (user uploaded) files
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
